name: mxnet-docs
dependencies:
- python
- jupyter
- sphinx
- matplotlib
- pandas
- notebook
- pip:
  - pyopenssl
  - nbsphinx
  - recommonmark
  - notedown
  - mxnet
  - pypandoc
  - sphinx_materialdesign_theme
  - breathe
