name: mxnet-docs
dependencies:
- python
- jupyter
- sphinx
- matplotlib
- pandas
- notebook
- pip:
  - pyopenssl
  - nbsphinx
  - recommonmark
  - notedown
  - mxnet
  - pypandoc
  - breathe
  - mock
  - awscli
  - git+https://github.com/rmk135/sphinxcontrib-disqus
  - https://github.com/szha/mx-theme/tarball/card
