name: mxnet-docs
dependencies:
- python
- jupyter
- sphinx
- matplotlib
- pandas
- notebook
- pip:
  - pyopenssl
  - nbsphinx
  - recommonmark
  - notedown
  - mxnet-cu92
  - pypandoc
  - sphinx_materialdesign_theme
  - breathe
  - mock
  - awscli
  - git+https://github.com/rmk135/sphinxcontrib-disqus
