name: mxnet-docs
channels:
- pytorch
dependencies:
- python
- jupyter
- sphinx
- matplotlib
- pandas
- notebook
- pytorch-cpu
- torchvision-cpu
- pip:
  - nbsphinx
  - recommonmark
  - notedown
  - mxnet-cu90==1.5.0b20190105
  - pypandoc
  - breathe
  - mock
  - awscli
  - git+https://github.com/rmk135/sphinxcontrib-disqus
  - https://github.com/mli/mx-theme/tarball/master
